apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    {{- include "edx.labels" . | nindent 4 }}
    kind: elasticsearch
spec:
  ports:
    - port: 9200
      protocol: TCP
  selector:
    {{- include "edx.selectorLabels" . | nindent 4 }}
    kind: elasticsearch

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    {{- include "edx.labels" . | nindent 4 }}
    kind: mysql
spec:
  ports:
    - port: 3306
      protocol: TCP
  selector:
    {{- include "edx.selectorLabels" . | nindent 4 }}
    kind: mysql

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    {{- include "edx.labels" . | nindent 4 }}
    kind: mongodb
spec:
  ports:
    - port: 27017
      protocol: TCP
  selector:
    {{- include "edx.selectorLabels" . | nindent 4 }}
    kind: mongodb

---
apiVersion: v1
kind: Service
metadata:
  name: memcached
  labels:
    {{- include "edx.labels" . | nindent 4 }}
    kind: memcached
spec:
  ports:
    - port: 11211
      protocol: TCP
  selector:
    {{- include "edx.selectorLabels" . | nindent 4 }}
    kind: memcached

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    {{- include "edx.labels" . | nindent 4 }}
    kind: rabbitmq
spec:
  ports:
    - port: 5672
      protocol: TCP
  selector:
    {{- include "edx.selectorLabels" . | nindent 4 }}
    kind: rabbitmq

