apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: edx-minio-env
  namespace: edx
spec:
  encryptedData:
    MINIO_ACCESS_KEY: AgA+Wm/c1dhkm+6zcgd+mmn5za4xpz19oED4ambZRMm8toLQNHIt8XJRKpdbNZyWISjEPJ6kwFMkgmWIT3b7EXKiztOG5Iku9xkCPjjf5LAGhoaVHZKfdlSeA8A16lUxZvhFHzYnISmqFnF4RiLyPe0cBv/tWhZ78NKzCS2rBCZLxmY0u9rJv3klTnniwnW29Rq4fXJPvPEM7ZRNQTFBYLCJSPq7mSVDVIt/afUwf3jlKjuuinbto0EG24wGYqCyuiai2yKv9BgrQ9r+088GkCyIaKSF/9x4D8ba6SWb2VxajPolAuOksX55Wg9q6k+NTOS2/o8hXBeohABXgbUV1F5moiXFG/j6l6YS+vh1Br+Jt9nk3/EJXVZ/xA2ANPTRTufQvn8mxFb3h8/8QC/Gu+kRHmucMkV4MrditQ3/iIfWGfv4yO1KOvp0lOngqFVonkLHCBp+5R+EZ+gC2E47rEEP58Fj7SQJz5dHRRhPmqqoSfFcBWUzgFOhZoRNQfrw5Sc9kDxF4ZTbPjRLWxyK0ohT9spFFfU//WMT08ZtySG0Kvc9lm9ZNiupO4+q0SXdACjFfUo9S1Ibsbm2dL+ceQj2Qx7hzTqvzYxhAG0Sr67pXYAm3RQESb+aTRyhKPAKEfkNcJsy4A0vwCAz6bs9ZGhe8PPtFH+yIMsMcG8c0dSsQOXRILsRz2Hf8UWg84iaQ0qTrpHXbk/Q5pwAObMEc4FOtVNS5+Jw0EQrqqGLmyYRv3DxfXpvqzQqeCivl+kliA==
    MINIO_SECRET_KEY: AgBnHTxgfZPpLWF2jsvJSat3ZAIC2BV3ItiuTnNr+ViZo7NaSGWaFc0Onbmbov++jvcB8whftQhoOL8ZJhYJE0SCchmz7NWkcB7GU3+Ah/P0d7F/cym/8/0tVA5q7uDosfMggXR2mO90fAc4dbQ1ebSLpUYYQHVltumz6GHEeteEF++m+uwXI71SoUI49FkTGvh1S+4yIzctubc4q1YQ1TZ2gPVa2EvPI+zvTp5jJHusLh90Y1UnrHk93+GE+wWIWi5dXzbIcg+nrxDbfFn1Z4DoatMLFtTtmFmPE9+wqXCaTIhIAUvN34DGfgoqQaYfKiXF3SHR77ZkkGvS0D2gdzVjB0VjKefJVqVoaUlhtTy2uAiTz2zrddwr9K4uqXxyP06Y1g2JeNE9F1TCwiDcZAZ7fc+YjkfW8uh5p8DmGb9VYFhXH2c8Cc5S28IZ+QGl4WXlrksAqW3XVAYFGzWv6lii0owlyB5ahgnJWPGWq4UamRJqmZ/fwY561mHOIZdNvmtcKUiFQd1Bczvt+cQ/ISkhNNWFabFpOrxMQyxtTbwxuQ8cUU6kMMuW+BUrNfLv/SejmVICV0cwkAYmNXW7owpWiG5SVkqAXGW/bvsw8GqIJ8qOCwDTIAlpEV1YzkmtMvaCdovybuZN562p0oTmKOKKsca6QmzuKu5r39TnPwA/Eq22Ios3Xim4wlj8yqVpSzclnn/czIs78wbz3gHlEvPeFTi6mp7otazI9parQtXU5ew028yMJeTuAnU2TIWhQLlnoM71Zn0=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: edx-minio-env
      namespace: edx

