apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: edx-mongodb-env
  namespace: edx
spec:
  encryptedData:
    MONGO_INITDB_ROOT_USERNAME: AgBz7wWlmvI7UVTw7tBWmJnvtGcJ7VM0ZSybMCNkdiJQpDjpxKNTLBvC+YIJLx/2OPex0yJTBJniefJE6iRHOdZLAxD/cmQpXuTUFbpKPXwjOjzqgPRfBAIUFs54H/I7g1zzSYTe87UlBJyP3fBb83SUh69wC5qT2DcF7Qye5dXUX+hh9+8iGrKoMDxZn+QIfSfTXx2o91v51iCy7hN2bwguVDbd/buyxUnwSM4NK7DjSZykF6JFidS7z5+yM08aZb13o4ovzUfDIRhEz+6iKped+tH//FQ5hDr/PNW07hn8jKWYt4qCK09YBFD4dXyVinoUH9gdAy4Tr/wWI+pZSGnbgpBryMC0yWIWFbwprDM3A/rq0FIEIbUGDH21btS3smeSM8JsKx9bADM5dSy/DjISsb2mfVwdJ0aw2zmhUwKzdwlvGgvKfNLeGhR0X0e35K1/eGjOkV1zpTepd9GJmP1ugvl0UVbcr38VWhBmV44CJ0Xb/sW380LaJpB8quptf42OVYTgsRq7bsRIQI4zmSlM1b8d7UMDs6LL9AKttmg59gXpq14tuILcvs1VfjzTNIgUatQfY3rZcOgVX1dSbBkUasVrpiIm+m3TwbLBiJdE3gwINGM6sTH9SEBDEvo9s0TbzySlh7ABg8XMNS4ZGNIBZ8QxBmQ6c/rN7ENooURA7RqdQnnmEhEDIzDIe1w+2pz3QiTyL/s=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: edx-mongodb-env
      namespace: edx

