apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: edx-mysql-env
  namespace: edx
spec:
  encryptedData:
    MYSQL_ROOT_PASSWORD: AgAVfjktPghyx2IY2XRQzZj4zR2H7ldcqwkrrZfWZIrrAUR50xIiEfqbfo5bBqy5TOZyS593qTY2pATk1LjpAPlGRgz/EQ0xbCV6yowfF+vnOYvBRLIupZgDzqsbzyLeVXzedR0LVEqv9VM2cl2kQQ5VI1MG+JqetG5SDGFXzHFfnug5znHMFSSa891kF4X+mFCGmROLfrbxE5IQaX26iVyWsxj7rWjo4bTCqYtN0zWZ8oVNCdTCtoiJVLGq5Xy/YtVMFDf2bJbr16srlU3uflWwMMsfACM0BDMeZA3z9c8CD1IsjFB5a9gkVk6o9ChAc51knMHN2eF0xYDOVNu3/61RCeMbE5hoPdufAjHMvfEWybhzzSd87jBxD01ftXYPFFDAOQEZvlgtn4uZGmZTf6EJbtSNy9tqpqYpAPU9SLRFuI8pBYkBFj4hAbWsjZlXYe3KwRkenw92YX6guUVxO2dGQWxE9Io0BTlq6tl0cmOg1bRPBuVYJxqipcb3seiFGMnOr2/fPGcvp5BipAqd46Pr9mbGeB4GBuAABiqF4bR0J6P+Dcgc+00plA++jLY2zNulJLavAwIfckJ2l7meyRmrg2L4bMHwvKdca+cT5YoEFBbB1MtCWdnwPBEdEPQNfXLKgMqh3Uys+59D9dAm8FEzemo0rkP9PcZ7KJfNPOXr7E/34LTd7wPzaCgmW6SyzuJng39GpL0DEjN3yA8q+I84JSJ9lRXNjROpFvZ4eWtBMbMf/nuQg9sPAtTyC4cIl4PAEyyVYCg=
    MYSQL_USER: AgAHpop72biaJwuwwkz7B4OegZalxQSgzOZqnhSYmdyFwdJ68ghndn/3c72HL3Z9j8V2YmxV6ThXPGCyVub88VBmK67WDu3ZQxYfovpeYTFrBpgCQvuE4Z/Cr1nrZcnLkPY8iCBpOGHXE9Bqnhy5MbopCzYS1excY1hY+EYN9+sdtDBL5+GrPK57iO623I2A5aXZqZ5yOBMsN0A9U6LsEdgHH9CBq/yqlYQ465pCtCmdZIAQDjqMtfCtSrFGXXu6l/TttyA3wUc6G53UkLMHbQT0p1IRqZZlu3EsFZZUnGT3KoC66LmtBAKHjL9eCx9hMU2xHGSIS/xlfGXpIun251hfuuNfb0Pf2ZpIq2RKPzOrmGuxcR+wNFR2eH42Jsxuu6mVj41BUEnOG5uYmmNZvgfQYl12pRgiU4U8+Qm1bo0zpjIejZHQGSM3WSRC3N+KhCPCYQLvO2RfP4lyZsNDTUy0VUVnN0sOBARUFzp7YKO8ljRattQkm9z3NZnyAVE+pHC/uZ9/VYzXjr0W+YVp0lwsHXTJMfb1NsBj7/rxLDZ2oijhEmPkwtGJLg6TR1aLeV8Rs8VqFaWU65ge/jkxY1TVD5CI+64G/xMmXhHs4ZGEuOThChXgQdSrFPx+BdMKvGokLVJCPh7pB+Fs3RyD+/yt6S+bQTtcCSaFdiW8zoGtUsHcVJe4gOaKc8YoiwhhmkwmuzSSsI8=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: edx-mysql-env
      namespace: edx

